name: kvnchat
services:
- name: web
  source_dir: /
  github:
    repo: nftecnologia/kvnchat
    branch: main
    deploy_on_push: true
  build_command: |
    bundle install --deployment --without development test
    pnpm install --frozen-lockfile
    BUILD_MODE=library bundle exec bin/vite build
    bundle exec bin/vite build
    DISABLE_SPRING=1 RAILS_ENV=production bundle exec rails assets:precompile
  run_command: |
    bundle exec rails ip_lookup:setup
    bundle exec rails runner "config = InstallationConfig.find_by(name: 'INSTALLATION_PRICING_PLAN'); config.update(value: 'enterprise') if config; GlobalConfig.clear_cache"
    bundle exec rails db:chatwoot_prepare
    bundle exec puma -C config/puma.rb
  environment_slug: ruby
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  health_check:
    http_path: /
    initial_delay_seconds: 120
    period_seconds: 30
    timeout_seconds: 10
    success_threshold: 1
    failure_threshold: 5
  routes:
  - path: /
  envs:
  - key: RAILS_ENV
    value: production
  - key: SECRET_KEY_BASE
    value: "12d7f1e8ee481d8b43290e9ebc37c9bc0a0c877c15619ae1874987d1a36234350b1788712491eb2f7ccdafd0e1404757ba4f307ad61117c8e90c0a7b2af18969"
    scope: RUN_AND_BUILD_TIME
  - key: FRONTEND_URL
    value: ${APP_URL}
  - key: DATABASE_URL
    type: SECRET
    value: ${POSTGRESQL_DATABASE_URL}
  - key: BUILD_DATABASE_URL
    value: "postgresql://dummy:dummy@localhost:5432/dummy_build_db"
    scope: BUILD_TIME
  - key: REDIS_URL
    value: ${UPSTASH_REDIS_URL}
  - key: REDIS_OPENSSL_VERIFY_MODE
    value: none
  - key: PORT
    value: "8080"
  - key: RAILS_LOG_TO_STDOUT
    value: "true"
  - key: FORCE_SSL
    value: "true"
  - key: ENABLE_ACCOUNT_SIGNUP
    value: "false"
  - key: MAILER_SENDER_EMAIL
    value: "noreply@seu-dominio.com"
  - key: ACTIVE_STORAGE_SERVICE
    value: "local"
  - key: RAILS_SERVE_STATIC_FILES
    value: "true"
  - key: CAPTAIN_ENABLED
    value: "true"
  - key: OPENAI_API_KEY
    type: SECRET
    value: ${OPENAI_API_KEY}
  - key: OPENAI_MODEL
    value: "gpt-4"
  - key: OPENAI_EMBEDDINGS_MODEL
    value: "text-embedding-ada-002"
  - key: RAILS_MASTER_KEY
    type: SECRET
    value: ${RAILS_MASTER_KEY}
  - key: ASSET_CDN_HOST
    value: ""
  - key: NODE_ENV
    value: production
  - key: RAILS_LOG_LEVEL
    value: info
  - key: DISABLE_DATABASE_ENVIRONMENT_CHECK
    value: "1"
  - key: SCHEMA
    value: "db/schema.rb"

- name: worker
  source_dir: /
  github:
    repo: nftecnologia/kvnchat
    branch: main
    deploy_on_push: true
  build_command: bundle install --deployment --without development test
  run_command: |
    bundle exec rails ip_lookup:setup
    bundle exec rails runner "config = InstallationConfig.find_by(name: 'INSTALLATION_PRICING_PLAN'); config.update(value: 'enterprise') if config; GlobalConfig.clear_cache"
    bundle exec sidekiq -C config/sidekiq.yml
  environment_slug: ruby
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: RAILS_ENV
    value: production
  - key: SECRET_KEY_BASE
    value: "12d7f1e8ee481d8b43290e9ebc37c9bc0a0c877c15619ae1874987d1a36234350b1788712491eb2f7ccdafd0e1404757ba4f307ad61117c8e90c0a7b2af18969"
    scope: RUN_AND_BUILD_TIME
  - key: DATABASE_URL
    type: SECRET
    value: ${POSTGRESQL_DATABASE_URL}
  - key: REDIS_URL
    value: ${UPSTASH_REDIS_URL}
  - key: REDIS_OPENSSL_VERIFY_MODE
    value: none
  - key: CAPTAIN_ENABLED
    value: "true"
  - key: OPENAI_API_KEY
    type: SECRET
    value: ${OPENAI_API_KEY}
  - key: RAILS_MASTER_KEY
    type: SECRET
    value: ${RAILS_MASTER_KEY}


