name: kvnchat
services:
- name: web
  source_dir: /
  github:
    repo: nftecnologia/kvnchat
    branch: main
    deploy_on_push: true
  build_command: |
    bundle install --deployment --without development test
    pnpm install --frozen-lockfile
    pnpm run build:sdk
    pnpm build 
    RAILS_ENV=production bundle exec rails assets:precompile
  run_command: |
    bundle exec rails db:create || true
    bundle exec rails db:migrate
    bundle exec puma -C config/puma.rb
  environment_slug: ruby
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  health_check:
    http_path: /
    initial_delay_seconds: 60
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  routes:
  - path: /
  envs:
  - key: RAILS_ENV
    value: production
  - key: SECRET_KEY_BASE
    type: SECRET
    value: ${SECRET_KEY_BASE}
  - key: FRONTEND_URL
    value: ${APP_URL}
  - key: DATABASE_URL
    type: SECRET
    value: ${DATABASE_URL}
  - key: REDIS_URL
    value: ${redis.DATABASE_URL}
  - key: REDIS_OPENSSL_VERIFY_MODE
    value: none
  - key: PORT
    value: "8080"
  - key: RAILS_LOG_TO_STDOUT
    value: "true"
  - key: FORCE_SSL
    value: "true"
  - key: ENABLE_ACCOUNT_SIGNUP
    value: "false"
  - key: MAILER_SENDER_EMAIL
    value: "noreply@seu-dominio.com"
  - key: ACTIVE_STORAGE_SERVICE
    value: "local"
  - key: RAILS_SERVE_STATIC_FILES
    value: "true"
  - key: CAPTAIN_ENABLED
    value: "true"
  - key: OPENAI_API_KEY
    type: SECRET
    value: ${OPENAI_API_KEY}
  - key: OPENAI_MODEL
    value: "gpt-4"
  - key: OPENAI_EMBEDDINGS_MODEL
    value: "text-embedding-ada-002"
  - key: RAILS_MASTER_KEY
    type: SECRET
    value: ${RAILS_MASTER_KEY}
  - key: ASSET_CDN_HOST
    value: ""
  - key: NODE_ENV
    value: production

- name: worker
  source_dir: /
  github:
    repo: nftecnologia/kvnchat
    branch: main
    deploy_on_push: true
  build_command: bundle install --deployment --without development test
  run_command: bundle exec sidekiq -C config/sidekiq.yml
  environment_slug: ruby
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: RAILS_ENV
    value: production
  - key: SECRET_KEY_BASE
    type: SECRET
    value: ${SECRET_KEY_BASE}
  - key: DATABASE_URL
    type: SECRET
    value: ${DATABASE_URL}
  - key: REDIS_URL
    value: ${redis.DATABASE_URL}
  - key: REDIS_OPENSSL_VERIFY_MODE
    value: none
  - key: CAPTAIN_ENABLED
    value: "true"
  - key: OPENAI_API_KEY
    type: SECRET
    value: ${OPENAI_API_KEY}
  - key: RAILS_MASTER_KEY
    type: SECRET
    value: ${RAILS_MASTER_KEY}

databases:
- name: redis
  engine: REDIS
  version: "7"
  production: false
  size: basic-xxs

